version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: booking-mysql
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: hotelbase
      MYSQL_USER: hoteladmin
      MYSQL_PASSWORD: hotelpass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    expose:
      - 3307
    volumes:
      - /var/lib/mysql
    restart: unless-stopped